# Generated by Django 5.0.3 on 2024-03-31 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
        ('projects', '0002_alter_project_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='tittle',
        ),
        migrations.AlterField(
            model_name='board',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
