# Generated by Django 5.0.3 on 2024-04-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_card_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='title',
            field=models.CharField(default='Testing Board', max_length=100),
        ),
    ]
