# Generated by Django 5.0.3 on 2024-04-03 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_board_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='tittle',
            new_name='title',
        ),
    ]
